version: '2.1'
networks:
  default:
     driver: nat
     name: news_default
services:  
  newsdb:
    image: microsoft/mssql-server-windows-express
    ports:
      - "1433:1433"
    restart: always
    networks:
      - default
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_YEULA: "Y"
  newsapi:
    image: newsapi
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: server/server/DockerFile
    links:
      - newsdb
    restart: always
    networks:
      - default
    environment:
      - DBHOST=newsdb
      - ASPNETCORE_ENVIRONMENT=Development
      - NewsDbConnection="data source=newsdb;initial catalog=NewsDB;"
  newsapp:
    image: newsapp
    ports:
      - "4200:4200"
    build:
      context: .
      dockerfile: frontend/DockerFile
    links:
      - newsdb
      - newsapi
    restart: always
    networks:
      - default
