FROM microsoft/aspnetcore:2.0-nanoserver-1709 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0-nanoserver-1709 AS build
WORKDIR /src
COPY server/server/server.csproj server/
RUN dotnet restore server/server/server.csproj
COPY . .
WORKDIR /src/server
RUN dotnet build server.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish server.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "server.dll"]